.github/contributing.md
- added base contributing md
---
=> Adds contributing file fixes #42

package.json
- Removed port assignment in package file
---
=> Removes port assignment in package file fixes #47

.env, src/Api/Game/getGames.jsx, src/Components/Game/gameListItem.jsx, src/Components/Layout.jsx
- Added api call to `getGames`
- Added GameListItem to hold the game object
---
=> Adds call to api for game list fixes #33

src/Api/Debug/seed.js, src/Components/Layout.jsx
- added api call to `/debug/seed`  
---
=> Adds call to seed the backend on load fixes #50

src/Components/Chat/ContentArea.jsx, src/Components/Chat/Hook.jsx, src/Components/Chat/hook.module.css
=> Adds hook message rendering fixes #30

SECURITY.md
- added...
- updated...
- removed...
---
=> Create base security md

.env, src/Components/Layout.jsx, src/Components/User/OnlineCard.jsx, src/Components/User/onlinecard.module.css
- added simulated call to get a logged in user
- updated layout to use the online card to represent the current user
---
=> Uses the online card to render a default/debug user fixes #31

src/Components/Layout.jsx
- added a simulated call to get playerlist  
---
=> Renders player list as a list of cards fixes #65

src/Components/Chat/comment.module.css, src/Components/Chat/contentArea.module.css, src/Components/layout.module.css
- added...
- updated...
- removed...
---
=>  reply box fix

.github/contributing.md
- Updated contributing.md with first draft
---
=> First draft of contributing file fixes #68

README.md
- Added first draft of readme
---
=> First draft of readme fixes #44

src/Api/Game/getRuleset.jsx, src/Components/Chat/ContentArea.jsx, src/Components/Game/gameListItem.jsx, src/Components/Game/gameListItem.module.css, src/Components/Layout.jsx, src/Components/Modals/ruleset.jsx, src/Components/layout.module.css
- added api call to get rules
- game list item
- removed...
---
=> Adds api call to ruleset and some game list styling fixes #12

package-lock.json, package.json, src/Components/Chat/ContentArea.jsx, src/Components/Chat/Reply.jsx, src/Components/Chat/reply.module.css
=> first iteration of socket handler fixes #35

src/Components/Chat/ContentArea.jsx, src/Components/Chat/Reply.jsx
=> fix lintint errors

package.json
- added...
- updated...
- removed...
---
=> Point linter to actual src

public/index.html, src/Components/Chat/ContentArea.jsx, src/Components/Chat/contentArea.module.css, src/Components/modal/Accordion.jsx, src/Components/modal/accordion.module.css, src/Components/modal/modal.jsx, src/Components/modal/modal.module.css
- added modal when game name is clicked
---
=> added modal when room name is clicked #37

src/Api/Authentication/signUp.jsx, src/Components/Layout.jsx
- added... sign in/sign up functionality
- updated...
- removed...
---
=> sign in/sign up fixes #7

src/Components/Chat/ContentArea.jsx, src/Components/Chat/contentArea.module.css, src/Components/Game/gameListItem.jsx, src/Components/Modals/Ruleset.jsx
- added...
- updated...
- removed...
---
=> 12 cleanup

src/Components/Chat/Reply.jsx
- added... text field clear on chat Reply
- updated...
- removed...
---
=> chat reply clears ..in-ine functions

src/Components/Chat/Reply.jsx
- added...
- updated...
- removed...
---
=> remove console log on #83

src/Components/Chat/ContentArea.jsx, src/Components/Layout.jsx
- added seed button
- updated chat to join current game instead of hardcode to blamegame_api
- removed...
---
=> Adds re-seed button instead of seed on load

src/Components/Chat/ContentArea.jsx
- added autoplay when getting a new hook message
- updated...
- removed...
---
=> Auto play audio when getting a hook

src/Components/Chat/ContentArea.jsx, src/Components/Layout.jsx
- added null/empty checks on currentGame  
---
=> Null or empty protection on currentGame

src/Components/Layout.jsx, src/Components/User/onlinecard.module.css, src/Components/layout.module.css
- updated loggedInUser css
- Removed some scroll bars and adjusted header height
- removed...
---
=> Adjusts logged in user css fixes #104

package-lock.json, package.json, src/Components/Chat/Comment.jsx, src/Components/Chat/Hook.jsx, src/Components/Chat/MessageLog.jsx, src/Components/GridLayout.jsx, src/Components/Layout.jsx, src/Components/Util/Player.jsx
- Swapped cookie lib
- Setting cookie after receiving to persist
- Random console error fixes 
---
=> Switch cookie pkg and persist cookie

src/Components/GridLayout.jsx
- Text entry didnt clear after hitting button
- updated...
- removed...
---
=> CLear text after hitting submit button

src/Components/Chat/Comment.jsx, src/Components/Chat/Hook.jsx, src/Components/Chat/MessageLog.jsx, src/Components/Chat/comment.module.css, src/Components/Chat/hook.module.css, src/Components/GridLayout.jsx, src/Components/Header/Header.jsx, src/Components/Header/header.module.css, src/Components/Sidebar/GameList.jsx, src/Components/User/LoggedInUser.jsx, src/Components/User/loggedInUser.module.css, src/Components/gridLayout.module.css
- added...
- updated...
- removed...
---
=> First cut at responsiveness
